name: Deploy to Production

on:
  push:
    branches:
      - main
      - develop
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t new-project-backend -f backend/Dockerfile .

      - name: Tag Docker image
        run: |
          docker tag new-project-backend jherrerogb98/fastapi_ai:new-project-backend

      - name: Push Docker image
        run: |
          docker push jherrerogb98/fastapi_ai:new-project-backend

      - name: Trigger Render deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_URL }}